const books =[
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},
{title:"Things fall apart", author:"chindr", pub:"05/13/10", type:"fiction"},






]
module.exports=books